// Static country and city options (replace with your data source if available)
export const countries = [
  { value: "العراق", label: "العراق" },
  { value: "مصر", label: "مصر" },
  { value: "السعودية", label: "السعودية" },
];

export const citiesByCountry: {
  [key: string]: { value: string; label: string }[];
} = {
    العراق: [
        { value: "بغداد", label: "بغداد" },
        { value: "البصرة", label: "البصرة" },
        { value: "الموصل", label: "الموصل" },
        { value: "الأنبار", label: "الأنبار" },
        { value: "بابل", label: "بابل" },
        { value: "الديوانية", label: "الديوانية" },
        { value: "ديالى", label: "ديالى" },
        { value: "ذي قار", label: "ذي قار" },
        { value: "السليمانية", label: "السليمانية" },
        { value: "صلاح الدين", label: "صلاح الدين" },
        { value: "كربلاء", label: "كربلاء" },
        { value: "كركوك", label: "كركوك" },
        { value: "ميسان", label: "ميسان" },
        { value: "المثنى", label: "المثنى" },
        { value: "النجف", label: "النجف" },
        { value: "واسط", label: "واسط" },
        { value: "أربيل", label: "أربيل" },
        { value: "دهوك", label: "دهوك" },
        { value: "حلبجة", label: "حلبجة" },
  ],
  مصر: [
    { value: "القاهرة", label: "القاهرة" },
    { value: "الجيزة", label: "الجيزة" },
    { value: "الإسكندرية", label: "الإسكندرية" },
    { value: "القليوبية", label: "القليوبية" },
    { value: "الدقهلية", label: "الدقهلية" },
    { value: "البحيرة", label: "البحيرة" },
    { value: "الغربية", label: "الغربية" },
    { value: "الشرقية", label: "الشرقية" },
    { value: "المنوفية", label: "المنوفية" },
    { value: "كفر الشيخ", label: "كفر الشيخ" },
    { value: "الفيوم", label: "الفيوم" },
    { value: "بني سويف", label: "بني سويف" },
    { value: "المنيا", label: "المنيا" },
    { value: "أسيوط", label: "أسيوط" },
    { value: "سوهاج", label: "سوهاج" },
    { value: "قنا", label: "قنا" },
    { value: "الأقصر", label: "الأقصر" },
    { value: "أسوان", label: "أسوان" },
    { value: "البحر الأحمر", label: "البحر الأحمر" },
    { value: "الوادي الجديد", label: "الوادي الجديد" },
    { value: "مطروح", label: "مطروح" },
    { value: "شمال سيناء", label: "شمال سيناء" },
    { value: "جنوب سيناء", label: "جنوب سيناء" },
    { value: "الإسماعيلية", label: "الإسماعيلية" },
    { value: "السويس", label: "السويس" },
    { value: "بورسعيد", label: "بورسعيد" },
    { value: "دمياط", label: "دمياط" },
  ],
  السعودية: [
    // منطقة الرياض
    { value: "الرياض", label: "الرياض" },
    { value: "الدرعية", label: "الدرعية" },
    { value: "الخرج", label: "الخرج" },
    { value: "الدوادمي", label: "الدوادمي" },
    { value: "المجمعة", label: "المجمعة" },
    { value: "القويعية", label: "القويعية" },
    { value: "وادي الدواسر", label: "وادي الدواسر" },
    { value: "الزلفي", label: "الزلفي" },
    { value: "شقراء", label: "شقراء" },
    { value: "حوطة بني تميم", label: "حوطة بني تميم" },
    { value: "عفيف", label: "عفيف" },
    { value: "السليل", label: "السليل" },
    { value: "ضرما", label: "ضرما" },
    { value: "المزاحمية", label: "المزاحمية" },
    { value: "رماح", label: "رماح" },
    { value: "ثادق", label: "ثادق" },
    { value: "حريملاء", label: "حريملاء" },
    { value: "الحريق", label: "الحريق" },
    { value: "مرات", label: "مرات" },
    { value: "الدلم", label: "الدلم" },
    { value: "الرين", label: "الرين" },
    // منطقة مكة المكرمة
    { value: "جدة", label: "جدة" },
    { value: "مكة", label: "مكة" },
    { value: "الطائف", label: "الطائف" },
    { value: "القنفذة", label: "القنفذة" },
    { value: "الليث", label: "الليث" },
    { value: "رابغ", label: "رابغ" },
    { value: "خليص", label: "خليص" },
    { value: "الخرمة", label: "الخرمة" },
    { value: "رنية", label: "رنية" },
    { value: "تربة", label: "تربة" },
    { value: "الجموم", label: "الجموم" },
    { value: "الكامل", label: "الكامل" },
    { value: "المويه", label: "المويه" },
    { value: "ميسان", label: "ميسان" },
    // منطقة المدينة المنورة
    { value: "المدينة المنورة", label: "المدينة المنورة" },
    { value: "ينبع", label: "ينبع" },
    { value: "العلا", label: "العلا" },
    { value: "بدر", label: "بدر" },
    { value: "خيبر", label: "خيبر" },
    { value: "العيص", label: "العيص" },
    { value: "وادي الفرع", label: "وادي الفرع" },
    // المنطقة الشرقية
    { value: "الدمام", label: "الدمام" },
    { value: "الهفوف", label: "الهفوف" },
    { value: "حفر الباطن", label: "حفر الباطن" },
    { value: "الجبيل", label: "الجبيل" },
    { value: "القطيف", label: "القطيف" },
    { value: "الخبر", label: "الخبر" },
    { value: "رأس تنورة", label: "رأس تنورة" },
    { value: "الخفجي", label: "الخفجي" },
    // منطقة القصيم
    { value: "بريدة", label: "بريدة" },
    { value: "عنيزة", label: "عنيزة" },
    { value: "الرس", label: "الرس" },
    { value: "البكيرية", label: "البكيرية" },
    { value: "البدائع", label: "البدائع" },
    { value: "النبهانية", label: "النبهانية" },
    { value: "الشماسية", label: "الشماسية" },
    { value: "عيون الجواء", label: "عيون الجواء" },
    { value: "رياض الخبراء", label: "رياض الخبراء" },
    { value: "عقلة الصقور", label: "عقلة الصقور" },
    // منطقة عسير
    { value: "أبها", label: "أبها" },
    { value: "خميس مشيط", label: "خميس مشيط" },
    { value: "بيشة", label: "بيشة" },
    { value: "محايل عسير", label: "محايل عسير" },
    { value: "سراة عبيدة", label: "سراة عبيدة" },
    // منطقة الحدود الشمالية
    { value: "عرعر", label: "عرعر" },
    // منطقة الجوف
    { value: "سكاكا", label: "سكاكا" },
    { value: "القريات", label: "القريات" },
    { value: "دومة الجندل", label: "دومة الجندل" },
    { value: "طبرجل", label: "طبرجل" },
    // منطقة جازان
    { value: "جيزان", label: "جيزان" },
    { value: "صبيا", label: "صبيا" },
    { value: "أبو عريش", label: "أبو عريش" },
    { value: "صامطة", label: "صامطة" },
    { value: "الدرب", label: "الدرب" },
    { value: "بيش", label: "بيش" },
    // منطقة نجران
    { value: "نجران", label: "نجران" },
    { value: "شرورة", label: "شرورة" },
    // منطقة تبوك
    { value: "تبوك", label: "تبوك" },
    { value: "تيماء", label: "تيماء" },
    { value: "حقل", label: "حقل" },
    { value: "الوجه", label: "الوجه" },
    // يمكن إضافة المزيد من المدن والمدينةات حسب الحاجة
  ]
};
